### ISSUE TITLE
hello，I download your annotation files from https://dataset.chenli.group/home/rcc-region-and-subtyping, but I can't download, can you share your annotation files? Thank you very much~~~

### ISSUE THREAD

**Issue by klforever0410** [ZeyuGaoAi/SSMTL_CancerClassification#3]
hello，I download your annotation files from https://dataset.chenli.group/home/rcc-region-and-subtyping, but I can't download, can you share your annotation files? Thank you very much~~~

**Comment by ZeyuGaoAi** [comment]
Sorry for the problem with our website, the download links are as follows:

https://drive.google.com/drive/folders/1SwUY-KDueq6k3l3eTWzt18nxVTVes7kw
https://drive.google.com/drive/folders/1g4qF_svzSglO4vAry4FTl6T_vocv9MxF
https://drive.google.com/drive/folders/1uLJrvjQUrTiBgnMSyWpfZ4cz1vMbNK1k


klforever0410 ***@***.***> 于2023年12月4日周一 02:37写道：
